apiVersion: v1
kind: Service
metadata:
  name: posts-svc #name of the service
spec:
  type: NodePort
  selector:
    app: posts #pods with the label to be selected
  ports:
    - name: posts
      protocol: TCP
      port: 4000 #Port in the service node which opens the access to target port
      targetPort: 4000 #Port in the pod/container that should be exposed
